# -*- coding: utf-8 -*-
"""sentiment_analysis_transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODhmzHQm40QQwx6UTGpwGFPtLUQ3Td-Z
"""

from transformers import pipeline

# Load sentiment analysis pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

# Example texts
texts = [
    "I love this course! It explains concepts so clearly.",
    "The movie was too long and boring.",
    "Amazing service and friendly staff!",
    "I don't think I will use this app again.",
    "Absolutely fantastic experience!"
]

# Run sentiment analysis
results = sentiment_pipeline(texts)

# Print results
for text, result in zip(texts, results):
    print(f"Text: {text}")
    print(f"Sentiment: {result['label']} | Score: {round(result['score'], 4)}")
    print("-" * 50)

